# Generated by Django 2.2.5 on 2019-09-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apistep',
            name='apimethod',
            field=models.CharField(choices=[('get', 'get'), ('post', 'post'), ('put', 'put'), ('delete', 'delete'), ('patch', 'patch')], default='get', max_length=200, null=True, verbose_name='方法'),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='apiparamvalue',
            field=models.CharField(max_length=800, verbose_name='参数和值'),
        ),
    ]
